apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: dev
type: Opaque
data:
  MYSQL_DATABASE: "ZGV2b3Bz"  # Base64 encoded value of "devops"
  MYSQL_ROOT_PASSWORD: "MTIzNDU2"  # Base64 encoded value of "123456"